"""API route metadata for the plugin.

Keeping this declarative table outside the plugin class makes the main module
easier to navigate while preserving MoviePilot's expected route dictionaries.
"""

from typing import Any, Dict, List, Tuple


RouteSpec = Tuple[str, str, Tuple[str, ...], str, str]


API_ROUTE_SPECS: Tuple[RouteSpec, ...] = (
    ("/status", "get_status", ("GET",), "bear", "获取媒体整理增强状态"),
    ("/config", "save_config_api", ("POST",), "bear", "保存媒体整理增强配置"),
    ("/preview", "preview_api", ("POST",), "bear", "试跑一次候选识别"),
    ("/history/clear", "clear_history_api", ("POST",), "bear", "清空识别历史"),
    (
        "/recognition-memory/clear",
        "clear_recognition_memory_api",
        ("POST",),
        "bear",
        "清空近期识别记忆",
    ),
    (
        "/anime-cross-id/status",
        "get_anime_cross_id_status_api",
        ("GET",),
        "bear",
        "获取动画跨站 ID 数据库状态",
    ),
    (
        "/anime-cross-id/refresh",
        "refresh_anime_cross_id_api",
        ("POST",),
        "bear",
        "后台更新动画跨站 ID 数据库",
    ),
    (
        "/episode-normalizer",
        "get_episode_normalizer_api",
        ("GET",),
        "bear",
        "获取集数归一化规则和季度条目",
    ),
    (
        "/episode-normalizer/rule",
        "save_episode_rule_api",
        ("POST",),
        "bear",
        "保存目标编集规则",
    ),
    (
        "/episode-normalizer/rule/delete",
        "delete_episode_rule_api",
        ("POST",),
        "bear",
        "删除目标编集规则",
    ),
    (
        "/episode-normalizer/rule/batch-delete",
        "batch_delete_episode_rules_api",
        ("POST",),
        "bear",
        "批量删除目标编集规则",
    ),
    (
        "/episode-normalizer/manual-add",
        "manual_add_episode_rule_api",
        ("POST",),
        "bear",
        "使用 TMDBID 手动建立目标编集规则",
    ),
    (
        "/episode-normalizer/inspect",
        "inspect_episode_target_api",
        ("POST",),
        "bear",
        "查看 TMDB 默认编集和剧集组",
    ),
    (
        "/episode-normalizer/preview",
        "preview_episode_normalizer_api",
        ("POST",),
        "bear",
        "试跑集数归一化",
    ),
    (
        "/episode-normalizer/catalog/query",
        "query_season_catalog_api",
        ("POST",),
        "bear",
        "按季度查询动画看板",
    ),
    (
        "/episode-normalizer/catalog/add",
        "add_season_catalog_rule_api",
        ("POST",),
        "bear",
        "从季度看板直接加入维护规则",
    ),
    (
        "/episode-normalizer/catalog/batch-add",
        "batch_add_season_catalog_rules_api",
        ("POST",),
        "bear",
        "批量匹配季度动画并加入维护规则",
    ),
    (
        "/episode-normalizer/emby-sync",
        "get_emby_sync_api",
        ("GET",),
        "bear",
        "获取 Emby 剧集组联动状态",
    ),
    (
        "/episode-normalizer/emby-sync/config",
        "save_emby_sync_config_api",
        ("POST",),
        "bear",
        "保存 Emby 剧集组联动设置",
    ),
    (
        "/episode-normalizer/emby-sync/preview",
        "preview_emby_sync_api",
        ("POST",),
        "bear",
        "只读试跑 Emby Series 定位",
    ),
    (
        "/episode-normalizer/emby-sync/apply-all",
        "apply_all_emby_sync_api",
        ("POST",),
        "bear",
        "将剧集组写入全部同 TMDBID Series",
    ),
    (
        "/episode-normalizer/emby-sync/retry",
        "retry_emby_sync_api",
        ("POST",),
        "bear",
        "重试 Emby 剧集组联动任务",
    ),
    (
        "/episode-normalizer/emby-sync/delete",
        "delete_emby_sync_job_api",
        ("POST",),
        "bear",
        "删除 Emby 剧集组联动任务",
    ),
    (
        "/metadata-tools/strm-sync",
        "get_strm_sync_api",
        ("GET",),
        "bear",
        "获取神医媒体信息推送设置与任务",
    ),
    (
        "/metadata-tools/strm-sync/config",
        "save_strm_sync_config_api",
        ("POST",),
        "bear",
        "保存神医媒体信息推送设置",
    ),
    (
        "/metadata-tools/strm-sync/preview",
        "preview_strm_sync_api",
        ("POST",),
        "bear",
        "对单个文件试推神医媒体信息",
    ),
    (
        "/metadata-tools/strm-sync/retry",
        "retry_strm_sync_api",
        ("POST",),
        "bear",
        "重试神医媒体信息推送任务",
    ),
    (
        "/metadata-tools/strm-sync/delete",
        "delete_strm_sync_job_api",
        ("POST",),
        "bear",
        "删除神医媒体信息推送任务",
    ),
    (
        "/metadata-tools",
        "get_metadata_tools_api",
        ("GET",),
        "bear",
        "获取制作组和重命名字段目录",
    ),
    (
        "/metadata-tools/release-group",
        "save_release_group_profile_api",
        ("POST",),
        "bear",
        "设置制作组类型",
    ),
    (
        "/metadata-tools/media-probe/preview",
        "preview_media_probe_api",
        ("POST",),
        "bear",
        "读取实际媒体流并预览命名字段",
    ),
    (
        "/metadata-tools/media-probe/cache/clear",
        "clear_media_probe_cache_api",
        ("POST",),
        "bear",
        "清除媒体流扫描缓存",
    ),
    (
        "/metadata-tools/media-probe/static-ffprobe/install",
        "install_static_ffprobe_api",
        ("POST",),
        "bear",
        "下载并安装 ISO 探测用静态 ffprobe",
    ),
    (
        "/metadata-tools/recognition-rule",
        "save_recognition_rule_api",
        ("POST",),
        "bear",
        "保存内置识别字段覆盖规则",
    ),
    (
        "/metadata-tools/recognition-rule/delete",
        "delete_recognition_rule_api",
        ("POST",),
        "bear",
        "删除内置识别字段覆盖规则",
    ),
    (
        "/metadata-tools/recognition-rule/priority/bulk",
        "bulk_recognition_rule_priority_api",
        ("POST",),
        "bear",
        "批量修改当前筛选识别规则的插件优先级",
    ),
    (
        "/metadata-tools/recognition-rule/preview",
        "preview_recognition_rule_api",
        ("POST",),
        "bear",
        "试算内置识别字段覆盖规则",
    ),
    (
        "/metadata-tools/rename-field",
        "save_custom_rename_field_api",
        ("POST",),
        "bear",
        "保存自定义重命名字段",
    ),
    (
        "/metadata-tools/rename-field/delete",
        "delete_custom_rename_field_api",
        ("POST",),
        "bear",
        "删除自定义重命名字段",
    ),
    (
        "/metadata-tools/rename-field/preview",
        "preview_custom_rename_fields_api",
        ("POST",),
        "bear",
        "试算自定义重命名字段",
    ),
    (
        "/metadata-tools/release-group-arrangement",
        "save_release_group_arrangement_api",
        ("POST",),
        "bear",
        "保存制作组名称、顺序和连接符规则",
    ),
    (
        "/metadata-tools/release-group-arrangement/delete",
        "delete_release_group_arrangement_api",
        ("POST",),
        "bear",
        "删除制作组编排规则",
    ),
    (
        "/metadata-tools/release-group-arrangement/preview",
        "preview_release_group_arrangement_api",
        ("POST",),
        "bear",
        "试算制作组名称、顺序和连接符",
    ),
    (
        "/metadata-tools/rename-mapping",
        "save_rename_mapping_api",
        ("POST",),
        "bear",
        "保存命名阶段映射规则",
    ),
    (
        "/metadata-tools/rename-mapping/delete",
        "delete_rename_mapping_api",
        ("POST",),
        "bear",
        "删除命名阶段映射规则",
    ),
    (
        "/metadata-tools/rename-mapping/preview",
        "preview_rename_mapping_api",
        ("POST",),
        "bear",
        "试算命名阶段映射规则",
    ),
    (
        "/notification-enhancer",
        "get_notification_enhancer_api",
        ("GET",),
        "bear",
        "获取通知接管状态、路由、记录与候选审批",
    ),
    (
        "/notification-enhancer/config",
        "save_notification_enhancer_config_api",
        ("POST",),
        "bear",
        "保存通知接管设置",
    ),
    (
        "/notification-enhancer/test",
        "test_notification_enhancer_api",
        ("POST",),
        "bear",
        "发送通知接管测试消息",
    ),
    (
        "/notification-enhancer/records/clear",
        "clear_notification_records_api",
        ("POST",),
        "bear",
        "清空入库通知记录",
    ),
    (
        "/notification-enhancer/digest/send",
        "send_notification_digest_api",
        ("POST",),
        "bear",
        "立即发送待汇总的入库失败摘要",
    ),
    (
        "/notification-enhancer/candidates",
        "query_notification_candidates_api",
        ("POST",),
        "bear",
        "查询季度集数规则审批候选",
    ),
    (
        "/notification-enhancer/candidates/action",
        "action_notification_candidates_api",
        ("POST",),
        "bear",
        "加入或忽略季度集数规则候选",
    ),
    (
        "/notification-enhancer/candidates/batch/send",
        "send_notification_candidate_batch_api",
        ("POST",),
        "bear",
        "立即生成并发送集数偏移候选批次",
    ),
    (
        "/notification-enhancer/candidates/collage/{batch_id}",
        "get_notification_candidate_collage_api",
        ("GET",),
        "apikey",
        "获取集数偏移候选海报拼图",
    ),
    ("/diagnostics", "get_diagnostics_api", ("GET",), "bear", "按需采样 MoviePilot 和插件性能"),
)


def build_api_routes(plugin: Any) -> List[Dict[str, Any]]:
    """Bind declarative route specs to one plugin instance."""

    return [
        {
            "path": path,
            "endpoint": getattr(plugin, endpoint_name),
            "methods": list(methods),
            "auth": auth,
            "summary": summary,
        }
        for path, endpoint_name, methods, auth, summary in API_ROUTE_SPECS
    ]
